### ISSUE TITLE
Settaggi Window

### ISSUE THREAD

**Issue by WinterWind33** [WinterWind33/TerraDiMezzo#11]
I settaggi sono: 
- larghezza: servono minimo 945 px per 7 immagini, con larghezza media di 100 px, quindi vedi un po tu come fare, anche con probabili tasti ecc..
- altezza: minimo di 400 px, con altezza media di 100 px

Li do ora senza saperne le conseguenze, quindi aspettati cambiamenti. 

SE MI CAGASSI OGNI TANTO TE NE SAREI GRATO <3

**Comment by Fico96** [comment]
va bine

**Comment by WinterWind33** [comment]
Lo fai da codice o da GUI?

**Comment by Fico96** [comment]
però mi devi dare qualche guida, se no cerco su internet come ti avevo detto l'altro giorno, mi avevi accennato ai tuoi appunti

**Comment by WinterWind33** [comment]
oOK, a casa ti faccio il file
