### ISSUE TITLE
3D? 

### ISSUE THREAD

**Issue by WinterWind33** [WinterWind33/TerraDiMezzo#15]
Ok, per 3D intendiamo qualcosa di più bello giusto? Come lo facciamo? 

BrainStorming aperto. 

p.s. dato che nelle issue non posso aggiungere più di 1 persona, taggo @emanueledomingo

**Comment by Fico96** [comment]
nono, 3D con anche gli occhialini,ok no..stavo scherzando

**Comment by WinterWind33** [comment]
Emh, fac iu. No seriamente, come lo facciamo?? tanto sarà sempre 2D, ma dato che l'aspetto deve essere bello... come????

**Comment by emanueledomingo** [comment]
Si facciamolo in 3D, lol.
